// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DataFrameExample
List DataFrameExample(const DataFrame& DF);
RcppExport SEXP _surveygraph_DataFrameExample(SEXP DFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type DF(DFSEXP);
    rcpp_result_gen = Rcpp::wrap(DataFrameExample(DF));
    return rcpp_result_gen;
END_RCPP
}
// DateExample
List DateExample(DateVector& dv, DatetimeVector& dtv);
RcppExport SEXP _surveygraph_DateExample(SEXP dvSEXP, SEXP dtvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector& >::type dv(dvSEXP);
    Rcpp::traits::input_parameter< DatetimeVector& >::type dtv(dtvSEXP);
    rcpp_result_gen = Rcpp::wrap(DateExample(dv, dtv));
    return rcpp_result_gen;
END_RCPP
}
// ListExamples
List ListExamples(const List& rparam);
RcppExport SEXP _surveygraph_ListExamples(SEXP rparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type rparam(rparamSEXP);
    rcpp_result_gen = Rcpp::wrap(ListExamples(rparam));
    return rcpp_result_gen;
END_RCPP
}
// MatrixExample
List MatrixExample(const NumericMatrix& orig);
RcppExport SEXP _surveygraph_MatrixExample(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(MatrixExample(orig));
    return rcpp_result_gen;
END_RCPP
}
// NumericVectorExample
List NumericVectorExample(const NumericVector& orig);
RcppExport SEXP _surveygraph_NumericVectorExample(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(NumericVectorExample(orig));
    return rcpp_result_gen;
END_RCPP
}
// RcppRNGs
DataFrame RcppRNGs(const int n);
RcppExport SEXP _surveygraph_RcppRNGs(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppRNGs(n));
    return rcpp_result_gen;
END_RCPP
}
// StringVectorExample
List StringVectorExample(const StringVector& orig);
RcppExport SEXP _surveygraph_StringVectorExample(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(StringVectorExample(orig));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_surveygraph_DataFrameExample", (DL_FUNC) &_surveygraph_DataFrameExample, 1},
    {"_surveygraph_DateExample", (DL_FUNC) &_surveygraph_DateExample, 2},
    {"_surveygraph_ListExamples", (DL_FUNC) &_surveygraph_ListExamples, 1},
    {"_surveygraph_MatrixExample", (DL_FUNC) &_surveygraph_MatrixExample, 1},
    {"_surveygraph_NumericVectorExample", (DL_FUNC) &_surveygraph_NumericVectorExample, 1},
    {"_surveygraph_RcppRNGs", (DL_FUNC) &_surveygraph_RcppRNGs, 1},
    {"_surveygraph_StringVectorExample", (DL_FUNC) &_surveygraph_StringVectorExample, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_surveygraph(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
