# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DataFrameExample <- function(DF) {
    .Call(`_surveygraph_DataFrameExample`, DF)
}

DateExample <- function(dv, dtv) {
    .Call(`_surveygraph_DateExample`, dv, dtv)
}

ListExamples <- function(rparam) {
    .Call(`_surveygraph_ListExamples`, rparam)
}

MatrixExample <- function(orig) {
    .Call(`_surveygraph_MatrixExample`, orig)
}

NumericVectorExample <- function(orig) {
    .Call(`_surveygraph_NumericVectorExample`, orig)
}

RcppRNGs <- function(n) {
    .Call(`_surveygraph_RcppRNGs`, n)
}

StringVectorExample <- function(orig) {
    .Call(`_surveygraph_StringVectorExample`, orig)
}

